# Generated by Django 5.2.1 on 2025-05-30 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookly_booking', '0001_initial'),
        ('bookly_rooms', '0002_alter_booklyrooms_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BooklyTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cash', 'Cash Payment'), ('gcash', 'GCash'), ('paymaya', 'Paymaya')], max_length=20)),
                ('payment_token', models.CharField(blank=True, max_length=100)),
                ('last_four_digits', models.CharField(blank=True, max_length=4)),
                ('cash_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bookly_booking.booklybooking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookly_rooms.booklyrooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
