# Generated by Django 5.2.1 on 2025-06-07 04:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookly_booking', '0002_booklytransaction'),
        ('bookly_rooms', '0002_alter_booklyrooms_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booklybooking',
            options={'ordering': ['-booking_date']},
        ),
        migrations.AddField(
            model_name='booklybooking',
            name='guest_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booklybooking',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booklybooking',
            name='guest_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booklybooking',
            name='guest_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='booklybooking',
            constraint=models.UniqueConstraint(fields=('room', 'booking_check_in', 'booking_check_out'), name='unique_booking_per_room_dates'),
        ),
    ]
