# Generated by Django 5.2.1 on 2025-06-08 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookly_booking', '0003_alter_booklybooking_options_and_more'),
        ('bookly_rooms', '0002_alter_booklyrooms_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booklybooking',
            name='unique_booking_per_room_dates',
        ),
        migrations.AddField(
            model_name='booklytransaction',
            name='reference_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='booklytransaction',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card Payment'), ('cash', 'Cash Payment')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='booklybooking',
            constraint=models.UniqueConstraint(condition=models.Q(('booking_status__in', ['confirmed', 'pending', 'reserved'])), fields=('room', 'booking_check_in', 'booking_check_out'), name='unique_booking_per_room_dates'),
        ),
    ]
