# Generated by Django 5.2.1 on 2025-05-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookly_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='booklyuser',
            managers=[
            ],
        ),
    ]
