# Generated by Django 5.2.1 on 2025-05-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookly_user', '0002_alter_booklyuser_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklyuser',
            old_name='if_property_owners',
            new_name='if_property_owner',
        ),
    ]
