# Generated by Django 5.2.1 on 2025-06-19 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookly_property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='booklyproperty',
            name='city_province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='bookly_property.cityprovince'),
        ),
        migrations.AddField(
            model_name='cityprovince',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='bookly_property.region'),
        ),
        migrations.AddField(
            model_name='booklyproperty',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='bookly_property.region'),
        ),
        migrations.AlterUniqueTogether(
            name='cityprovince',
            unique_together={('region', 'name')},
        ),
    ]
