# Generated by Django 5.2.1 on 2025-05-26 17:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookly_property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooklyRooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('hotel', 'Hotel'), ('apartment', 'Apartment'), ('suite', 'Suite'), ('motel', 'Motel'), ('villa', 'Villa'), ('resort', 'Resort'), ('lodge', 'Lodge'), ('inn', 'Inn')], max_length=20)),
                ('room_description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('room_image', models.ImageField(upload_to='room_main_image/')),
                ('amenities', models.JSONField()),
                ('room_status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied')], default='available', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='bookly_property.booklyproperty')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('is_primary', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bookly_rooms.booklyrooms')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
    ]
